# HAMMER模型配置文件

# 图像配置
image_res: 256
vision_width: 768

# 模型配置
embed_dim: 256
temp: 0.07
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 50
label_smoothing: 0.0

# 损失权重
loss_MAC_wgt: 0.1
loss_BIC_wgt: 1
loss_bbox_wgt: 0.1
loss_giou_wgt: 0.1
loss_TMG_wgt: 1
loss_MLC_wgt: 1

# BERT配置
bert_config: 'bert-base-uncased'

# 训练参数
batch_size_train: 64
batch_size_val: 256

# 优化器参数
optimizer:
  opt: adamW
  lr: 1e-4
  weight_decay: 0.02

# 学习率调度器
schedular:
  sched: cosine
  lr: 1e-4
  epochs: 50
  min_lr: 1e-6
  decay_rate: 1
  warmup_lr: 1e-6
  warmup_epochs: 10
  cooldown_epochs: 0 